### ISSUE TITLE
ResultTemplates: use @babel/code-frame

### ISSUE THREAD

**Issue by AriPerkkio** [AriPerkkio/eslint-remote-tester#18]
Use `code-frame` for `result.source`.

https://github.com/AriPerkkio/eslint-remote-tester/blob/5cfd453fd44a0132b03ee8ad513dd8a917685698/lib/file-client/result-templates.ts#L44-L58

https://babeljs.io/docs/en/babel-code-frame

- Breaking change

**Comment by AriPerkkio** [comment]
## Rule: unable-to-parse-rule-id

-   Message: `Cannot read property 'someAttribute' of undefined Occurred while linting <text>:2`
-   Path: `AriPerkkio/eslint-remote-tester-integration-test-target/expected-to-crash-linter.js`
-   [Link](https://github.com/AriPerkkio/eslint-remote-tester-integration-test-target/blob/HEAD/expected-to-crash-linter.js#L2)

```js
  1 | // Identifier.name = attributeForCrashing
> 2 | window.attributeForCrashing();
  3 | 
```

```
TypeError: Cannot read property 'someAttribute' of undefined
Occurred while linting <text>:2
    at Identifier (/<removed>/eslint-remote-tester/eslint-local-rules.js:21:56)
    at /<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /<removed>/eslint-remote-tester/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

## Rule: no-undef

-   Message: `'bar' is not defined.`
-   Path: `AriPerkkio/eslint-remote-tester-integration-test-target/index.js`
-   [Link](https://github.com/AriPerkkio/eslint-remote-tester-integration-test-target/blob/HEAD/index.js#L1-L1)

```js
> 1 | var foo = bar;
    |           ^^^
  2 | 
  3 | if (foo) {
  4 | }
```

## Rule: no-empty

-   Message: `Empty block statement.`
-   Path: `AriPerkkio/eslint-remote-tester-integration-test-target/index.js`
-   [Link](https://github.com/AriPerkkio/eslint-remote-tester-integration-test-target/blob/HEAD/index.js#L3-L4)

```js
  1 | var foo = bar;
  2 | 
> 3 | if (foo) {
    |          ^
> 4 | }
    | ^^
  5 | 
  6 | var p = {
  7 |     get name(){
```

## Rule: getter-return

-   Message: `Expected to return a value in getter 'name'.`
-   Path: `AriPerkkio/eslint-remote-tester-integration-test-target/index.js`
-   [Link](https://github.com/AriPerkkio/eslint-remote-tester-integration-test-target/blob/HEAD/index.js#L7-L7)

```js
   5 | 
   6 | var p = {
>  7 |     get name(){
     |     ^^^^^^^^
   8 |         // no returns.
   9 |     }
  10 | };
```

## Rule: no-compare-neg-zero

-   Message: `Do not use the '===' operator to compare against -0.`
-   Path: `AriPerkkio/eslint-remote-tester-integration-test-target/index.js`
-   [Link](https://github.com/AriPerkkio/eslint-remote-tester-integration-test-target/blob/HEAD/index.js#L14-L14)

```js
  12 | 
  13 | 
> 14 | if (foo === -0) {
     |     ^^^^^^^^^^
  15 |   // prevent no-empty
  16 | }
```
